-- Ajout des plans Majestic Club manquants
INSERT INTO subscription_plans (
  id, 
  plan_id, 
  name, 
  subtitle, 
  description, 
  price, 
  price_note, 
  features, 
  icon, 
  popular, 
  sort_order, 
  is_active, 
  subscription_type, 
  assigned_role, 
  assistance_level, 
  created_at, 
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'majestic_access',
  'Majestic Access',
  'Accès Premium aux services exclusifs',
  'Accédez à notre conciergerie de luxe avec assistance prioritaire et avantages exclusifs',
  499,
  'par mois',
  ARRAY[
    'Assistance 24/7 prioritaire',
    'Conciergerie personnelle',
    'Réservations prioritaires',
    'Accès aux lounges VIP',
    'Transport premium',
    'Support dédié'
  ],
  'crown',
  false,
  10,
  true,
  'premium',
  'majestic_member',
  'priority',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'majestic_prive',
  'Majestic Privé',
  'Expérience ultra-exclusive et personnalisée',
  'Le summum de l''exclusivité avec service sur mesure et privilèges uniques',
  999,
  'par mois',
  ARRAY[
    'Tout Majestic Access +',
    'Chef personnel privé',
    'Yacht et jet privé',
    'Événements exclusifs',
    'Conseiller dédié 24/7',
    'Assistance mondiale illimitée'
  ],
  'gem',
  true,
  11,
  true,
  'vip',
  'majestic_vip',
  'exclusive',
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'majestic_black',
  'Majestic Black',
  'Le nec plus ultra du luxe et du service',
  'Expérience Black Card avec accès illimité et service sans limites',
  1999,
  'par mois',
  ARRAY[
    'Tout Majestic Privé +',
    'Black Card personnelle',
    'Accès illimité partout',
    'Équipe personnelle dédiée',
    'Investissements exclusifs',
    'Hébergements privés'
  ],
  'shield',
  false,
  12,
  true,
  'ultra_vip',
  'majestic_black',
  'unlimited',
  NOW(),
  NOW()
);

-- Ajout des tarifications correspondantes
INSERT INTO subscription_pricing (
  id,
  plan_id,
  billing_cycle,
  price,
  currency,
  discount_percentage,
  trial_days,
  setup_fee,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'majestic_access',
  'monthly',
  327000,
  'XOF',
  0,
  7,
  0,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'majestic_access',
  'yearly',
  3270000,
  'XOF',
  10,
  14,
  0,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'majestic_prive',
  'monthly',
  655000,
  'XOF',
  0,
  14,
  0,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'majestic_prive',
  'yearly',
  6550000,
  'XOF',
  15,
  30,
  0,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'majestic_black',
  'monthly',
  1310000,
  'XOF',
  0,
  30,
  0,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'majestic_black',
  'yearly',
  13100000,
  'XOF',
  20,
  60,
  0,
  NOW(),
  NOW()
);
